-- =========================================================================================
-- 🚂 INDIAN RAILWAY STAFF EVALUATION SYSTEM (RSES)
-- SUPABASE PRODUCTION SCHEMA PROVISIONING SCRIPT
-- =========================================================================================
-- This script generates the complete, production-ready relational database architecture.
-- It includes Table Creations, Foreign Keys, Constraints, Indexes, and Role Seeding.
-- Designed for PostgreSQL 15+ (Supabase compatible).
-- =========================================================================================

-- Enable UUID extension for secure primary keys
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================================================================
-- 1. MASTER METADATA TABLES
-- =========================================================================================

-- ROLE: Defines system access levels and UI rendering rules.
CREATE TABLE "ROLE" (
    "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_name" VARCHAR(50) UNIQUE NOT NULL,
    "role_description" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- DIVISION: Broad geographical and administrative jurisdictions.
CREATE TABLE "DIVISION" (
    "division_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "division_name" VARCHAR(100) UNIQUE NOT NULL,
    "zone_name" VARCHAR(100) NOT NULL DEFAULT 'Central Railway',
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- STATION: Physical railway stations linked to a specific division.
CREATE TABLE "STATION" (
    "station_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "division_id" INT NOT NULL REFERENCES "DIVISION"("division_id") ON DELETE RESTRICT,
    "station_name" VARCHAR(150) UNIQUE NOT NULL,
    "station_code" VARCHAR(10) UNIQUE NOT NULL,
    "location" VARCHAR(255),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================================================
-- 2. CORE USERS & CREDENTIALS
-- =========================================================================================

-- USERS: Centralized credentials and cross-system identity mapping.
CREATE TABLE "USERS" (
    "user_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "role_id" INT NOT NULL REFERENCES "ROLE"("role_id") ON DELETE RESTRICT,
    "hrms_id" VARCHAR(50) UNIQUE NOT NULL,
    "full_name" VARCHAR(200) NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "mobile_no" VARCHAR(20) NOT NULL,
    "username" VARCHAR(100) UNIQUE NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "status" VARCHAR(20) NOT NULL DEFAULT 'Active' CHECK ("status" IN ('Active', 'Suspended', 'Retired')),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================================================
-- 3. EMPLOYEE HIERARCHY & ROLE SUBTYPES
-- =========================================================================================

CREATE TABLE "SUPER_ADMIN" (
    "super_admin_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID UNIQUE NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE
);

CREATE TABLE "AOM" (
    "aom_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID UNIQUE NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "zone" VARCHAR(100) NOT NULL DEFAULT 'Central Railway',
    "join_date" DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE "TRAFFIC_INSPECTOR" (
    "ti_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID UNIQUE NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "station_id" INT REFERENCES "STATION"("station_id") ON DELETE SET NULL,
    "jurisdiction" VARCHAR(255) NOT NULL,
    "reporting_aom" INT REFERENCES "AOM"("aom_id") ON DELETE SET NULL
);

CREATE TABLE "STATION_SUPERINTENDENT" (
    "ss_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID UNIQUE NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "station_id" INT REFERENCES "STATION"("station_id") ON DELETE RESTRICT,
    "joining_date" DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE "STATION_MASTER" (
    "sm_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID UNIQUE NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "station_id" INT REFERENCES "STATION"("station_id") ON DELETE RESTRICT,
    "joining_date" DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE "TRAIN_MANAGER" (
    "tm_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID UNIQUE NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "station_id" INT REFERENCES "STATION"("station_id") ON DELETE RESTRICT,
    "joining_date" DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE "POINTSMAN" (
    "pm_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID UNIQUE NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "sm_id" INT REFERENCES "STATION_MASTER"("sm_id") ON DELETE SET NULL, -- Establishes PM -> SM reporting line
    "shift" VARCHAR(50) NOT NULL CHECK ("shift" IN ('Morning Shift (06:00 - 14:00)', 'Evening Shift (14:00 - 22:00)', 'Night Shift (22:00 - 06:00)')),
    "work_location" VARCHAR(150) NOT NULL,
    "joining_date" DATE NOT NULL DEFAULT CURRENT_DATE
);


-- =========================================================================================
-- 4. PROFILE, MEDICAL, AND TRAINING REGISTRIES
-- =========================================================================================

CREATE TABLE "EMPLOYEE_PROFILE" (
    "profile_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" UUID UNIQUE NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "dob" DATE NOT NULL,
    "joining_date" DATE NOT NULL DEFAULT CURRENT_DATE,
    "qualification" VARCHAR(150),
    "address" TEXT,
    "blood_group" VARCHAR(10)
);

CREATE TABLE "PME_RECORD" (
    "pme_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "pme_due_date" DATE NOT NULL,
    "pme_done_date" DATE,
    "pme_status" VARCHAR(50) NOT NULL DEFAULT 'Fit' CHECK ("pme_status" IN ('Fit', 'Unfit', 'Temporary Unfit', 'Overdue')),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "TRAINING_RECORD" (
    "training_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "course_name" VARCHAR(150) NOT NULL,
    "training_date" DATE NOT NULL,
    "expiry_date" DATE NOT NULL,
    "status" VARCHAR(50) NOT NULL CHECK ("status" IN ('Cleared', 'Overdue', 'Exempted')),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "MONITORING" (
    "monitoring_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID UNIQUE NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "monitoring_status" VARCHAR(50) NOT NULL DEFAULT 'Active' CHECK ("monitoring_status" IN ('Active', 'Suspended', 'Under Observation')),
    "risk_level" VARCHAR(20) NOT NULL DEFAULT 'Low' CHECK ("risk_level" IN ('Low', 'Medium', 'High')),
    "remarks" TEXT,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================================================
-- 5. ASSESSMENT & QUESTION BANK SYSTEM
-- =========================================================================================

CREATE TABLE "QUESTION_BANK" (
    "question_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_id" INT NOT NULL REFERENCES "ROLE"("role_id") ON DELETE RESTRICT,
    "section_name" VARCHAR(100) NOT NULL,
    "question_text" TEXT NOT NULL,
    "option_a" VARCHAR(255) NOT NULL,
    "option_b" VARCHAR(255) NOT NULL,
    "option_c" VARCHAR(255) NOT NULL,
    "option_d" VARCHAR(255) NOT NULL,
    "correct_option" CHAR(1) NOT NULL CHECK ("correct_option" IN ('A', 'B', 'C', 'D')),
    "marks" INT NOT NULL DEFAULT 1,
    "is_active" BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE "ASSESSMENT" (
    "assessment_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "employee_id" UUID NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "conducted_by" UUID NOT NULL REFERENCES "USERS"("user_id") ON DELETE RESTRICT,
    "assessment_type" VARCHAR(100) NOT NULL,
    "assessment_date" DATE NOT NULL DEFAULT CURRENT_DATE,
    "due_date" DATE,
    "status" VARCHAR(50) NOT NULL DEFAULT 'Pending' CHECK ("status" IN ('Draft', 'Pending', 'Approved', 'Rejected')),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "TEST_ATTEMPT" (
    "attempt_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "assessment_id" UUID NOT NULL REFERENCES "ASSESSMENT"("assessment_id") ON DELETE CASCADE,
    "employee_id" UUID NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "total_marks" INT NOT NULL,
    "obtained_marks" INT NOT NULL,
    "percentage" DECIMAL(5,2) NOT NULL,
    "category" CHAR(1) NOT NULL CHECK ("category" IN ('A', 'B', 'C', 'D')),
    "started_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "submitted_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ANSWER_HISTORY" (
    "answer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "attempt_id" UUID NOT NULL REFERENCES "TEST_ATTEMPT"("attempt_id") ON DELETE CASCADE,
    "question_id" INT NOT NULL REFERENCES "QUESTION_BANK"("question_id") ON DELETE RESTRICT,
    "selected_option" CHAR(1) NOT NULL CHECK ("selected_option" IN ('A', 'B', 'C', 'D')),
    "is_correct" BOOLEAN NOT NULL,
    "correct_option" CHAR(1) NOT NULL,
    "marks_obtained" INT NOT NULL DEFAULT 0
);


-- =========================================================================================
-- 6. MULTI-TIER APPROVAL & WORKFLOW ROUTING
-- =========================================================================================

CREATE TABLE "APPROVAL" (
    "approval_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "assessment_id" UUID UNIQUE NOT NULL REFERENCES "ASSESSMENT"("assessment_id") ON DELETE CASCADE,
    "approved_by" UUID NOT NULL REFERENCES "USERS"("user_id") ON DELETE RESTRICT,
    "approval_level" VARCHAR(50) NOT NULL DEFAULT 'Traffic Inspector' CHECK ("approval_level" IN ('Traffic Inspector', 'Station Master')),
    "approval_date" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "remarks" TEXT
);

CREATE TABLE "REVIEW" (
    "review_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "approval_id" UUID UNIQUE NOT NULL REFERENCES "APPROVAL"("approval_id") ON DELETE CASCADE,
    "reviewed_by" UUID NOT NULL REFERENCES "USERS"("user_id") ON DELETE RESTRICT,
    "review_level" VARCHAR(50) NOT NULL DEFAULT 'AOM',
    "review_date" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "remarks" TEXT
);


-- =========================================================================================
-- 7. AUDIT LOGS, SAFETY RECORDS, & REPORTS
-- =========================================================================================

CREATE TABLE "SAFETY_RECORD" (
    "safety_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" UUID NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "incident_type" VARCHAR(50) NOT NULL CHECK ("incident_type" IN ('Inspection', 'Counseling', 'Accident')),
    "incident_date" DATE NOT NULL,
    "description" TEXT NOT NULL,
    "action_taken" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "REPORT" (
    "report_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "generated_by" VARCHAR(100) NOT NULL,
    "report_type" VARCHAR(100) NOT NULL,
    "generated_date" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "file_path" TEXT NOT NULL
);

CREATE TABLE "NOTIFICATION" (
    "notification_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "title" VARCHAR(200) NOT NULL,
    "message" TEXT NOT NULL,
    "is_read" BOOLEAN NOT NULL DEFAULT FALSE,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "AUDIT_LOG" (
    "log_id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "user_id" UUID REFERENCES "USERS"("user_id") ON DELETE SET NULL,
    "action" VARCHAR(100) NOT NULL,
    "table_name" VARCHAR(50) NOT NULL,
    "record_id" VARCHAR(100),
    "timestamp" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "ip_address" INET
);


-- =========================================================================================
-- 8. INDEXES FOR QUERY OPTIMIZATION
-- =========================================================================================
-- Optimizing User Lookups
CREATE INDEX "idx_users_hrms" ON "USERS"("hrms_id");
CREATE INDEX "idx_users_role" ON "USERS"("role_id");
CREATE INDEX "idx_users_email" ON "USERS"("email");

-- Optimizing Geographical & Subtype Lookups
CREATE INDEX "idx_station_division" ON "STATION"("division_id");
CREATE INDEX "idx_pointsman_sm" ON "POINTSMAN"("sm_id");
CREATE INDEX "idx_ti_station" ON "TRAFFIC_INSPECTOR"("station_id");

-- Optimizing Core Evaluation Workflows
CREATE INDEX "idx_assessment_employee" ON "ASSESSMENT"("employee_id");
CREATE INDEX "idx_assessment_status" ON "ASSESSMENT"("status");
CREATE INDEX "idx_test_attempt_assessment" ON "TEST_ATTEMPT"("assessment_id");
CREATE INDEX "idx_answer_history_attempt" ON "ANSWER_HISTORY"("attempt_id");
CREATE INDEX "idx_approval_assessment" ON "APPROVAL"("assessment_id");
CREATE INDEX "idx_review_approval" ON "REVIEW"("approval_id");

-- Optimizing Registries
CREATE INDEX "idx_safety_record_user" ON "SAFETY_RECORD"("user_id");
CREATE INDEX "idx_pme_record_user" ON "PME_RECORD"("user_id");
CREATE INDEX "idx_notification_user" ON "NOTIFICATION"("user_id");
CREATE INDEX "idx_audit_log_timestamp" ON "AUDIT_LOG"("timestamp" DESC);


-- =========================================================================================
-- 9. PRODUCTION SEED DATA (ROLES)
-- =========================================================================================

-- Seed critical role hierarchy enforcing system constraints.
-- Uses hardcoded IDs to ensure reliable foreign key references during the migration phase.
INSERT INTO "ROLE" ("role_id", "role_name", "role_description") VALUES
(1, 'Super Admin', 'System administrator with global access and configuration privileges.'),
(2, 'AOM/General', 'Assistant Operations Manager overseeing divisional safety compliance and reviews.'),
(3, 'Traffic Inspector', 'Safety officer responsible for audits, counseling, and evaluating operational staff.'),
(4, 'Station Superintendent', 'Oversees multiple station masters and high-level station logistics.'),
(5, 'Station Master', 'Manages daily station operations and evaluates pointsmen compliance.'),
(6, 'Train Manager', 'Responsible for train movement safety and emergency brake evaluations.'),
(7, 'Pointsman', 'Performs ground-level shunting, coupling, and track safety operations.')
ON CONFLICT ("role_id") DO UPDATE 
SET "role_name" = EXCLUDED."role_name", 
    "role_description" = EXCLUDED."role_description";

