-- ====================================================================
-- Indian Railway Staff Evaluation & Competency System (RSES)
-- High-Performance PostgreSQL Database Provisioning & Seed Script
-- Safe to run in Supabase SQL Query Console - Handles Existing Tables cleanly
-- ====================================================================

-- 1. CLEANUP / DROP EXISTING TABLES IF NEEDED
-- (Cascades foreign keys automatically to ensure clean rebuild)
DROP TABLE IF EXISTS "SAFETY_RECORD" CASCADE;
DROP TABLE IF EXISTS "ANSWER_HISTORY" CASCADE;
DROP TABLE IF EXISTS "TEST_ATTEMPT" CASCADE;
DROP TABLE IF EXISTS "ASSESSMENT" CASCADE;
DROP TABLE IF EXISTS "QUESTION_BANK" CASCADE;
DROP TABLE IF EXISTS "EMPLOYEE_PROFILE" CASCADE;
DROP TABLE IF EXISTS "USERS" CASCADE;
DROP TABLE IF EXISTS "ROLE" CASCADE;
DROP TABLE IF EXISTS "STATION" CASCADE;
DROP TABLE IF EXISTS "DIVISION" CASCADE;

-- 2. CREATE SYSTEM TABLES WITH INTEGRITY CONSTRAINTS

-- Role Table
CREATE TABLE "ROLE" (
    "role_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role_name" VARCHAR UNIQUE NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Division Table
CREATE TABLE "DIVISION" (
    "division_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "division_name" VARCHAR UNIQUE NOT NULL,
    "division_code" VARCHAR UNIQUE NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Station Table
CREATE TABLE "STATION" (
    "station_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "station_name" VARCHAR UNIQUE NOT NULL,
    "station_code" VARCHAR UNIQUE NOT NULL,
    "division_id" INT REFERENCES "DIVISION"("division_id") ON DELETE CASCADE,
    "zone" VARCHAR NOT NULL DEFAULT 'Central Railway',
    "category" VARCHAR NOT NULL DEFAULT 'A',
    "platforms" INT DEFAULT 2,
    "tracks" INT DEFAULT 2,
    "status" VARCHAR NOT NULL DEFAULT 'Active' CHECK ("status" IN ('Active', 'Inactive')),
    "avg_score" INT DEFAULT 80,
    "safety_compliance" INT DEFAULT 100,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Users Table
CREATE TABLE "USERS" (
    "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "hrms_id" VARCHAR UNIQUE NOT NULL,
    "username" VARCHAR UNIQUE NOT NULL,
    "full_name" VARCHAR NOT NULL,
    "mobile_no" VARCHAR NOT NULL DEFAULT '—',
    "email" VARCHAR UNIQUE NOT NULL,
    "password" VARCHAR NOT NULL DEFAULT 'password123',
    "password_hash" VARCHAR NULL,
    "role_id" INT REFERENCES "ROLE"("role_id") ON DELETE RESTRICT,
    "division" VARCHAR NOT NULL DEFAULT 'Nagpur',
    "gender" VARCHAR NOT NULL DEFAULT 'Male',
    "age" INT DEFAULT 35,
    "status" VARCHAR NOT NULL DEFAULT 'Active' CHECK ("status" IN ('Active', 'Suspended', 'Retired')),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Employee Profile Table
CREATE TABLE "EMPLOYEE_PROFILE" (
    "profile_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT REFERENCES "USERS"("user_id") ON DELETE CASCADE UNIQUE,
    "station_id" INT REFERENCES "STATION"("station_id") ON DELETE SET NULL,
    "current_score" INT DEFAULT 80,
    "safety_score" INT DEFAULT 85,
    "pme_status" VARCHAR DEFAULT 'Fit',
    "refresher_status" VARCHAR DEFAULT 'Cleared',
    "disciplinary_record" VARCHAR DEFAULT 'None',
    "incidents_count" INT DEFAULT 0,
    "monitoring_status" VARCHAR DEFAULT 'Active',
    "date_of_joining" VARCHAR DEFAULT '2018-06-15',
    "reporting_sm" VARCHAR DEFAULT '—',
    "work_location" VARCHAR DEFAULT 'Yard Area',
    "shift" VARCHAR DEFAULT 'Morning Shift (06:00 - 14:00)',
    "jurisdiction" VARCHAR DEFAULT 'Nagpur Division',
    "category" VARCHAR DEFAULT 'A',
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
-- Assessment Engine Schedule Table
CREATE TABLE "ASSESSMENT" (
    "assessment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "assessment_type" VARCHAR NOT NULL,
    "assessment_date" VARCHAR NOT NULL,
    "status" VARCHAR NOT NULL DEFAULT 'Scheduled' CHECK ("status" IN ('Scheduled', 'Completed', 'Approved', 'Reviewed', 'Overdue')),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Test Attempts Table
CREATE TABLE "TEST_ATTEMPT" (
    "attempt_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "employee_id" INT REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "assessment_id" INT REFERENCES "ASSESSMENT"("assessment_id") ON DELETE CASCADE,
    "total_marks" REAL NOT NULL DEFAULT 100.0,
    "obtained_marks" REAL NOT NULL,
    "percentage" REAL NOT NULL,
    "category" VARCHAR NOT NULL DEFAULT 'A' CHECK ("category" IN ('A', 'B', 'C', 'D')),
    "started_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "completed_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Safety Record / Operational Incidents Table
CREATE TABLE "SAFETY_RECORD" (
    "incident_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT REFERENCES "USERS"("user_id") ON DELETE CASCADE,
    "incident_type" VARCHAR NOT NULL,
    "incident_date" VARCHAR NOT NULL,
    "severity" VARCHAR NOT NULL,
    "remarks" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. DISABLE ROW LEVEL SECURITY (RLS) FOR FULL ADMINISTRATIVE PRIVILEGES
-- (Prevents silent blank returns from Supabase clients querying via Anon Key)
ALTER TABLE "ROLE" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "DIVISION" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "STATION" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "USERS" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "EMPLOYEE_PROFILE" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "ASSESSMENT" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "TEST_ATTEMPT" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "SAFETY_RECORD" DISABLE ROW LEVEL SECURITY;

-- 4. SEED STANDARD OPERATIONAL PRIVILEGES AND ROLE GROUPS
INSERT INTO "ROLE" ("role_name") VALUES 
('Super Admin'),
('AOM/General'),
('Traffic Inspector'),
('Station Superintendent'),
('Train Manager'),
('Station Master'),
('Pointsman');

-- Seed Nagpur Division
INSERT INTO "DIVISION" ("division_name", "division_code") VALUES 
('Nagpur Division', 'NGP');

-- 5. SEED STANDARD RAILWAY STATION LISTS
-- (Removed as requested. System starts with a clean slate for station registration.)

-- 6. SEED KEY SYSTEM USER ACCOUNTS WITH ASSIGNED DESIGNATION ROLES
-- (All default passwords set to 'password123' for ease of testing)

-- Super Admin User
INSERT INTO "USERS" ("hrms_id", "username", "full_name", "email", "password", "role_id", "division", "gender", "age", "status") 
VALUES ('ADMIN_01', 'admin_01', 'Prof. Pathak', 'admin@rail.in', 'password123', 1, 'Nagpur', 'Male', 48, 'Active');

-- AOM/SRDOM User
INSERT INTO "USERS" ("hrms_id", "username", "full_name", "email", "password", "role_id", "division", "gender", "age", "status") 
VALUES ('AOM_NGP', 'aom_ngp', 'P. K. Verma (Sr. DOM)', 'srdom@rail.in', 'password123', 2, 'Nagpur', 'Male', 45, 'Active');

-- 7. SEED PROFILES ASSOCIATING PERSONNEL
-- (Profiles seeded with NULL station_id to align with clean-slate station structure)

-- Super Admin Profile
INSERT INTO "EMPLOYEE_PROFILE" ("user_id", "station_id", "current_score", "safety_score", "pme_status", "refresher_status", "date_of_joining", "reporting_sm", "work_location", "shift", "jurisdiction", "category") 
VALUES (1, NULL, 95, 98, 'Fit', 'Cleared', '2010-04-12', '—', 'HQ Office', 'General Shift (09:00 - 18:00)', 'Division Level', 'A');

-- AOM Profile
INSERT INTO "EMPLOYEE_PROFILE" ("user_id", "station_id", "current_score", "safety_score", "pme_status", "refresher_status", "date_of_joining", "reporting_sm", "work_location", "shift", "jurisdiction", "category") 
VALUES (2, NULL, 92, 95, 'Fit', 'Cleared', '2012-08-15', '—', 'HQ Office', 'General Shift (09:00 - 18:00)', 'Division Level', 'A');

-- ====================================================================
-- PROVISIONING AND SEEDING SEQUENCE COMPLETED SUCCESSFULLY
-- ====================================================================
